name: github-actions
on: [push]
jobs:
  selenium-local-run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: browser-actions/setup-chrome@latest
      - run: chromium --version
      - run: yarn install
      - run: yarn test tests/localdriver
  selenium-remote-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-firefox:4.0.0-rc-1-prerelease-20210804
      - run: yarn test tests/remote
  # selenium-parallel-run:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #     - run: npm install -g bats
  #     - run: bats -v
  # selenium-multibrowser-run:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #     - run: npm install -g bats
  #     - run: bats -v
